name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn

      - run: yarn install

      - name: Lint
        run: yarn lint

      - name: Check types
        run: yarn tsc

      - name: Run tests
        run: yarn test

      - name: Build
        run: yarn build
